name: Playwright tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.APP_BASE_URL }}
      EMAIL_USERNAME: ${{ secrets.APP_EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.APP_EMAIL_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest playwright
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium
      - name: Run tests
        run: |
          pytest -q